# Theme appearance
colorScheme = "ocean"  # ocean, fire, forest, etc.
defaultAppearance = "dark"  # light, dark, auto
autoSwitchAppearance = true

# Site features
enableSearch = true
enableCodeCopy = true
showScrollToTop = true

# Site icons
[site]
  favicon = "/favicon.png"

# Article settings
[article]
  showDate = true
  showDateUpdated = true
  showAuthor = true
  showReadingTime = true
  showTableOfContents = true
  showTaxonomies = true
  showWordCount = true
  sharingLinks = ["twitter", "linkedin", "reddit", "hackernews"]

# Homepage layout
[homepage]
  layout = "profile"  # page, profile, hero, card, background
  showRecent = true
  recentLimit = 5

# Author info
[author]
  name = "Miska Hämäläinen"
  # image = "/img/avatar.jpg"  # Commented out - will add later with full URL
  headline = "Security & Software Engineer"
  bio = "Specializing in Identity and Access Management, zero-trust security frameworks, and infrastructure automation. Building practical security solutions that teams actually use."
  email = "contact@miska.dev"
  links = [
    { email = "mailto:contact@miska.dev" },
    { github = "https://github.com/miskahm" },
    { linkedin = "https://www.linkedin.com/in/miska-hämäläinen/" },
  ]

# Footer
[footer]
  showCopyright = true
  copyright = "© 2025 Miska Hämäläinen"
  showThemeAttribution = true
  showAppearanceSwitcher = true
  showScrollToTop = true

# Custom CSS
[params]
  customCSS = ["css/custom.css"]
